from PFNExperiments.LatentFactorModels.GenerativeModels.FactorAnalysis.BasicFA import make_fa_program_normal_weight_prior as make_fa_program_normal_weight_prior_pyro
from PFNExperiments.LatentFactorModels.GenerativeModels.Numpyro_Versions.BasicFA import make_fa_program_normal_weight_prior as make_fa_program_normal_weight_prior_numpyro

from PFNExperiments.LatentFactorModels.GenerativeModels.FactorAnalysis.BasicFA import make_fa_program_laplace_weight_prior as make_fa_program_laplace_weight_prior_pyro
from PFNExperiments.LatentFactorModels.GenerativeModels.Numpyro_Versions.BasicFA import make_fa_program_laplace_weight_prior as make_fa_program_laplace_weight_prior_numpyro

from PFNExperiments.LatentFactorModels.GenerativeModels.FactorAnalysis.BasicFA import make_fa_program_normal_weight_prior_laplace_z_prior as make_fa_program_normal_weight_prior_laplace_z_prior_pyro	
from PFNExperiments.LatentFactorModels.GenerativeModels.Numpyro_Versions.BasicFA import make_fa_program_normal_weight_prior_laplace_z_prior as make_fa_program_normal_weight_prior_laplace_z_prior_numpyro

from PFNExperiments.LatentFactorModels.GenerativeModels.Clustering.GMMs import make_gmm_program_diagonal as make_gmm_program_diagonal_pyro
from PFNExperiments.LatentFactorModels.GenerativeModels.Numpyro_Versions.GMM_Numpyro import make_gmm_program_diagonal as make_gmm_program_diagonal_numpyro

"""
Simply map the Pyro code to Numpyro code
"""

pyro_ppgram2_numpyro_ppgram = {
    str(make_fa_program_normal_weight_prior_pyro.__name__): make_fa_program_normal_weight_prior_numpyro,
    str(make_fa_program_laplace_weight_prior_pyro.__name__): make_fa_program_laplace_weight_prior_numpyro,
    str(make_fa_program_normal_weight_prior_laplace_z_prior_pyro.__name__): make_fa_program_normal_weight_prior_laplace_z_prior_numpyro,
    str(make_gmm_program_diagonal_pyro.__name__): make_gmm_program_diagonal_numpyro,

}

if __name__ == "__main__":
    print(pyro_ppgram2_numpyro_ppgram)